config/routes.rb
Rails.application.routes.draw do

  root 'formularies#index'

  devise_for :users

  resources :formularies
  scope "/admin" do
    resources :users
  end

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    delete "/logout" => "devise/sessions#destroy"
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new #guest user
    if user.has_role? :admin
      can :manage, User
      can :manage, Formulary
    elsif user.has_role? :jurisdictional
      can :capture_formulary
      can :manage, Formulary
    elsif user.has_role? :state
      can :view_state_results #As Formulary is a REST resource i can erase this
      can :read, Formulary
    elsif user.has_role? :institutional
        can :view_institutional_results
    elsif user.has_role? :federal
        can :view_national_results
    else
      can :read, Formulary
    end
  end
end

app/models/formulary.rb
class Formulary < ActiveRecord::Base
  belongs_to :user

  def self.jurisdictional_results (*args)
    self.where(user_id: args)
  end

  def self.state_results (id)
    self.find_by_sql("select * from formularies as f inner join users as s on s.id = f.user_id inner join jurisdictions as j on j.id = s.jurisdiction_id inner join states as st on j.state_id = st.id where st.id= #{id}")
  end

end

app/models/jurisdiction.rb
class Jurisdiction < ActiveRecord::Base
  has_many :users
  belongs_to :state
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  scopify
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :jurisdictions
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  belongs_to :jurisdiction
  has_many :formularies
  after_create :default_role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable, :timeout_in => 15.minutes

  def self.users_from_jurisdiction(jurisdiction_id)
    Array.new.tap do |a|
    users = User.select("id").where("jurisdiction_id = ?", jurisdiction_id)
    users.each {|u| a << u.id }
    end
  end

  private
  def default_role
    User.last().add_role :jurisdictional
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  #This is important shit
  before_action do
    resource = controller_name.singularize.to_sym
    method = "#{resource}_params"
    params[resource] &&= send(method) if respond_to?(method, true)
  end

  protect_from_forgery with: :exception

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:name, :ap_paterno, :ap_materno, :jurisdiction_id  ]
  end

  rescue_from CanCan::AccessDenied do |exception|
  flash[:error] = "Acceso denegado."
  redirect_to root_url
end

end

app/controllers/formularies_controller.rb
class FormulariesController < ApplicationController
  load_and_authorize_resource
  def index
    if can? :capture_formulary, @user
      @formularios = Formulary.jurisdictional_results(User.users_from_jurisdiction(current_user.jurisdiction_id))
      render 'jurisdictional_results' 
    elsif can? :view_state_results, @user
      @formularios = Formulary.state_results(current_user.jurisdiction.state.id)
      render 'state_results'
    elsif can? :view_national_results, @user
      #@formularios = Formulary.resultados_nacionales
    else
      #@formularios = Formulary.formularios_jurisdiccionales(current_user.jurisdiction_id).order.page(params[:page]).per(5)
      #render partial: 'generic_partial' # renders app/views/products/_product.html.haml
      render 'generic_partial'
    end
    #render partial: 'product' # renders app/views/products/_product.html.haml
  end

  def show
  end

  def new
    @formulary = Formulary.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @formulario }
    end
  end

  def edit
  end

  def create
  if  @formulary = Formulary.create(formulary_params)
    respond_to do |format|
      format.html {redirect_to root_path}
    end
  else
    format.html { render :new }
  end
  end

  def update
    respond_to do |format|
      if @formulary.update(formulary_params)
        format.html { redirect_to @formulary, notice: 'Tu registro se ha actualizado.' }
        format.json { render :show, status: :ok, location: @formulary }
      else
        format.html { render :edit }
        format.json { render json: @formulary.errors, status: :unprocessable_entity }
      end
    end
  end



  def destroy
    @formulary.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Registro eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Using a private method to encapsulate the permissible parameters is
    # just a good pattern since you'll be able to reuse the same permit
    # list between create and update. Also, you can specialize this method
    # with per-user checking of permissible attributes.
    def formulary_params
      allow = [:responsable_llenado,:cod01,:cod02,:ape01,:ape04,:ape07,:ape02,:ape05,:ape03,:ape06,:api01,:api04,:api02,:ssb01,:api03,:cao01,:cao04,:cao07,:cao10,:tit01,:cao02,:cao05,:cao08,:cao11,:cao03,:cao06,:cao09,:cao12,:uni01,:uni02,:uni03,:ben01,:ben02,:per01,:per02,:user_id]
      params.require(:formulary).permit(allow)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/formularies_helper.rb
module FormulariesHelper
end

app/views/formularies/_form.html.erb
<%= form_for @formulary, :validate => true do |f| %>
  <% if @formulary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@formulary.errors.count, "error") %> prohibited this formulario from being saved:</h2>
      <ul>
      <% @formulary.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<form role="form">
<div class="row">
  <div class="col-md-2">
    <div class="form-group">
      <label>Responsable de llenado</label>
      <%= f.text_field :responsable_llenado, class: "form-control"%>
    </div>
  </div>
  <div class="col-md-1"></div>
</div>

  <div class="row">
    <div class="alert alert-info col-md-10">
      <strong>Consultas odontológicas</strong>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <div class="form-group">
        <label>COD01: Primera Vez</label>
        <%= f.number_field :cod01, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-2"></div>
    <div class="col-md-2">
        <div class="form-group">
          <label>COD02: Subsecuente</label>
          <%= f.number_field :cod02, options = {min: 1, class: "form-control"} %>
        </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-10 alert alert-info">
      <p>
        <strong>Actividades Preventivas:</strong> Intramuros y extramuros
      </p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <div class="form-group">
        <label>APE01: Detección de placa bacteriana*</label>
        <%= f.number_field :ape01, options = {min: 1, class: "form-control"} %>
      </div>

      <div class="form-group">
        <label>APE04: Enjuagues de fluoruro de sodios (Autoaplicaciones)*</label>
        <%= f.number_field :ape04, options = {min: 1, class: "form-control"} %>
      </div>

      <div class="form-group">
        <label>APE07: Instrucción de autoexamen de cavidad bucal </label>
        <%= f.number_field :ape07, options = {min: 1, class: "form-control"} %>
      </div>
    </div>
    <div class="col-md-2"></div>
    <div class="col-md-2">
      <div class="form-group">
        <label>APE02: Instrucción en técnica de cepillado*</label>
        <%= f.number_field :ape02, options = {class: "form-control"} %>
      </div>
      <div class="form-group">
        <label>APE05: Revisión de tejidos bucales*</label>
        <%= f.number_field :ape05, options = {class: "form-control"} %>
      </div>
    </div>
    <div class="col-md-2"></div>
    <div class="col-md-2">
      <div class="form-group">
       <label>APE03: Instrucción de uso del hilo dental </label>
        <%= f.number_field :ape03, options = {class: "form-control"} %>
      </div>
      <div class="form-group">
        <label>APE06: Revisión e instrucción de higiene de protésis*</label>
        <%= f.number_field :ape06, options = {class: "form-control"} %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-10 alert alert-info">
      <p>
        <strong>Actividades Preventivas:</strong> Intramuros
      </p>
    </div>
  </div>

<div class="row">
  <div class="col-md-2">
    <div class="form-group">
      <label>API01: Profilaxis</label>
      <%= f.number_field :api01, options = {class: "form-control"} %>
    </div>
    <div class="form-group">
      <label>API04: Sellado de fosetas y fisuras </label>
      <%= f.number_field :api04, options = {class: "form-control"} %>
    </div>
  </div>
  <div class="col-md-2"></div>
  <div class="col-md-2">
    <div class="form-group">
      <label>API02: Odontoxesis </label>
      <%= f.number_field :api02 , options = {class: "form-control"}%>
    </div>
    <div class="form-group">
      <label>SSB01: Sesiones sobre Salud Bucal</label>
      <%= f.number_field :ssb01 , options = {class: "form-control"}%>
    </div>
  </div>
  <div class="col-md-2"></div>
  <div class="col-md-2">
    <div class="form-group">
     <label>API03: Aplicación tópica de fluor</label>
      <%= f.number_field :api03, options = {class: "form-control"} %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-10 alert alert-info">
    <p>
      <strong>Curativo asistencial</strong>
    </p>
  </div>
</div>

<div class="row">
  <div class="col-md-2">
    <div class="form-group">
      <label>CAO01: Obturación con Amalgama</label>
      <%= f.number_field :cao01, options = {class: "form-control"} %>
    </div>
    <div class="form-group">
      <label>CAO04: Tratamiento restaurativo atraumático (extramuros)</label>
      <%= f.number_field :cao04, options = {class: "form-control"} %>
    </div>
    <div class="form-group">
      <label>CAO07: Extracciones Permanentes</label>
      <%= f.number_field :cao07 , options = {class: "form-control"}%>
    </div>
    <div class="form-group">
      <label>CAO10: Farmacoterapia</label>
      <%= f.number_field :cao10, options = {class: "form-control"} %>
    </div>
    <div class="form-group">
      <label>TIT01: Tratamiento Integral Terminado</label>
      <%= f.number_field :tit01 , options = {class: "form-control"}%>
    </div>
  </div>
  <div class="col-md-2"></div>

  <div class="col-md-2">
    <div class="form-group">
      <label>CAO02: Obturación con Resina</label>
      <%= f.number_field :cao02, options = {class: "form-control"} %>
    </div>
    <div class="form-group">
      <label>CAO05: Obturación con material temporal</label>
      <%= f.number_field :cao05, options = {class: "form-control"} %>
    </div>
    <div class="form-group">
      <label>CAO08: Terapia Pulpar</label>
      <%= f.number_field :cao08 , options = {class: "form-control"}%>
    </div>
    <div class="form-group">
      <label>CAO11: Otras Atenciones</label>
      <%= f.number_field :cao11 , options = {class: "form-control"}%>
    </div>
  </div>

  <div class="col-md-2"></div>

  <div class="col-md-2">
    <div class="form-group">
      <label>CAO03: Obturación con ionómetro de vidrio</label>
      <%= f.number_field :cao03, options = {class: "form-control"} %>
    </div>
    <div class="form-group">
      <label>CAO06: Extracciones Temporales</label>
      <%= f.number_field :cao06, options = {class: "form-control"} %>
    </div>
    <div class="form-group">
      <label>CAO09: Cirugía Bucal</label>
      <%= f.number_field :cao09 , options = {class: "form-control"}%>
    </div>
    <div class="form-group">
      <label>CAO12: Radiografías</label>
      <%= f.number_field :cao12 , options = {class: "form-control"}%>
    </div>
  </div>
</div>

  <div class="row">
    <div class="col-md-10 alert alert-info">
      <p>
        <strong>Universo</strong>
      </p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <div class="form-group">
        <label>UNI01: Escuelas</label>
        <%= f.number_field :uni01, options = {class: "form-control"} %>
      </div>
    </div>
    <div class="col-md-2"></div>
    <div class="col-md-2">
      <div class="form-group">
       <label>UNI02: Unidades de salud</label>
        <%= f.number_field :uni02 , options = {class: "form-control"}%>
      </div>
    </div>
    <div class="col-md-2"></div>
    <div class="col-md-2">
      <div class="form-group">
        <label>UNI03: Otros(ferias de salud, plazas, mercados, etc.)</label>
        <%= f.number_field :uni03 , options = {class: "form-control"}%>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-10 alert alert-info">
      <p>
        <strong>Beneficiados</strong>
      </p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <div class="form-group">
        <label>BEN01: Menores de 20 años</label>
        <%= f.number_field :ben01, options = {class: "form-control"} %>
      </div>
    </div>
    <div class="col-md-2"></div>
    <div class="col-md-2">
      <div class="form-group">
        <label>BEN02: 20 años ó más</label>
        <%= f.number_field :ben02, options = {class: "form-control"} %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-10 alert alert-info">
      <p>
        <strong>Personal participante</strong>
      </p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <div class="form-group">
        <label>PER01: Personal de salud</label>
        <%= f.number_field :per01 %>
      </div>
    </div>
    <div class="col-md-2"></div>

    <div class="col-md-2">
      <div class="form-group">
        <label>PER02: Otros</label>
        <%= f.number_field :per02 %>
      </div>
    </div>
    <div class="col-md-2"></div>
    <div class="col-md-2">
      <div class="form-group">
        <%= f.hidden_field :user_id, :value => current_user.id, :readonly => true  %>
      </div>
    </div>
  </div>
<div class="actions">
  <%= f.submit "Guardar", :confirmation => true %>
</div>
</form>
<% end %>

app/views/formularies/_state_results.html.erb
<h1>State results</h1>

app/views/formularies/create.html.erb
<h1>Formularies#create</h1>
<p>Find me in app/views/formularies/create.html.erb</p>

app/views/formularies/destroy.html.erb
<h1>Formularies#destroy</h1>
<p>Find me in app/views/formularies/destroy.html.erb</p>

app/views/formularies/edit.html.erb
<h1>Edita el registro</h1>

<%= render 'form' %>
<%= link_to 'Volver', formularies_path %>

app/views/formularies/generic_partial.html.erb
<h2>Generic template</h2>
<p>
  Este es el generic template
</p>

app/views/formularies/index.html.erb
<h1>Este es el Index papaw!</h1>

app/views/formularies/jurisdictional_results.html.erb
<h2>Resultados</h2>
<% if @formularios.empty? %>
<div class="row">
  <div class="alert alert-info col-md-10">
    <strong>No se ha capturado ninguna meta.</strong>
  </div>
</div>
<% else %>
<div class="row">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th class="col-sm-4">Captura por:</th>
        <th class="col-sm-1"></th>
        <th class="col-sm-1"></th>
        <th class="col-sm-1"></th>
      </tr>
    </thead>
    <tbody>
      <% @formularios.each do |formulary| %>
        <tr>
          <td><%= formulary.responsable_llenado %></td>
          <td><%= link_to 'Detalles', formulary %></td>
          <td><%= link_to 'Editar', edit_formulary_path(formulary) %></td>
          <td><%= link_to 'Eliminar', formulary, method: :delete, data: { confirm: '¿Seguro?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>
<%= link_to("Nueva captura", new_formulary_path, nil) %>

app/views/formularies/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="span10">
      <h1>Metas programadas para Semana Nacional de Salud Bucal</h1>
    </div>
  </div>
</div>
<br />
<br />

<%= render 'form' %>

<%= link_to 'Volver', formularies_path %>

app/views/formularies/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Cod01:</b>
  <%= @formulary.cod01 %>
</p>

<p>
  <b>Cod02:</b>
  <%= @formulary.cod02 %>
</p>

<p>
  <b>Ape01:</b>
  <%= @formulary.ape01 %>
</p>

<p>
  <b>Ape02:</b>
  <%= @formulary.ape02 %>
</p>

<p>
  <b>Ape03:</b>
  <%= @formulary.ape03 %>
</p>

<p>
  <b>Ape04:</b>
  <%= @formulary.ape04 %>
</p>

<p>
  <b>Ape05:</b>
  <%= @formulary.ape05 %>
</p>

<p>
  <b>Ape06:</b>
  <%= @formulary.ape06 %>
</p>

<p>
  <b>Ape07:</b>
  <%= @formulary.ape07 %>
</p>

<p>
  <b>Api01:</b>
  <%= @formulary.api01 %>
</p>

<p>
  <b>Api02:</b>
  <%= @formulary.api02 %>
</p>

<p>
  <b>Api03:</b>
  <%= @formulary.api03 %>
</p>

<p>
  <b>Api04:</b>
  <%= @formulary.api04 %>
</p>

<p>
  <b>Ssb01:</b>
  <%= @formulary.ssb01 %>
</p>

<p>
  <b>Cao01:</b>
  <%= @formulary.cao01 %>
</p>

<p>
  <b>Cao02:</b>
  <%= @formulary.cao02 %>
</p>

<p>
  <b>Cao03:</b>
  <%= @formulary.cao03 %>
</p>

<p>
  <b>Cao04:</b>
  <%= @formulary.cao04 %>
</p>

<p>
  <b>Cao05:</b>
  <%= @formulary.cao05 %>
</p>

<p>
  <b>Cao06:</b>
  <%= @formulary.cao06 %>
</p>

<p>
  <b>Cao07:</b>
  <%= @formulary.cao07 %>
</p>

<p>
  <b>Cao08:</b>
  <%= @formulary.cao08 %>
</p>

<p>
  <b>Cao09:</b>
  <%= @formulary.cao09 %>
</p>

<p>
  <b>Cao10:</b>
  <%= @formulary.cao10 %>
</p>

<p>
  <b>Cao11:</b>
  <%= @formulary.cao11 %>
</p>

<p>
  <b>Cao12:</b>
  <%= @formulary.cao12 %>
</p>

<p>
  <b>Tit01:</b>
  <%= @formulary.tit01 %>
</p>

<p>
  <b>Uni01:</b>
  <%= @formulary.uni01 %>
</p>

<p>
  <b>Uni02:</b>
  <%= @formulary.uni02 %>
</p>

<p>
  <b>Uni03:</b>
  <%= @formulary.uni03 %>
</p>

<p>
  <b>Ben01:</b>
  <%= @formulary.ben01 %>
</p>

<p>
  <b>Ben02:</b>
  <%= @formulary.ben02 %>
</p>

<p>
  <b>Per01:</b>
  <%= @formulary.per01 %>
</p>

<p>
  <b>Per02:</b>
  <%= @formulary.per02 %>
</p>

<%= link_to 'Editar', edit_formulary_path(@formulary) %> |
<%= link_to 'Volver', root_path %>

app/views/formularies/state_results.html.erb
<h2>Los resultados se están procesando mientras el nivel jurisdiccional se encuentre capturando.</h2>
<h2>Los resultados a nivel estatal estarán listos el día 25 de Noviembre del presente.</h2>

app/views/formularies/update.html.erb
<h1>Formularies#update</h1>
<p>Find me in app/views/formularies/update.html.erb</p>

app/views/layouts/_footer.html.erb
<div class="container text-center">
    <hr />
    <div class="row">
        <div class="col-lg-12">
            <ul class="nav nav-pills nav-justified">
              <% if user_signed_in? %>
                <li><a href="/">Hola <%= current_user.email %></a></li>
              <% else %>
                <li><a href="#">Accede</a></li>
              <% end %>
                <li><a href="#">Versión 1.0.0</a></li>
                <li><a href="#">© 2015 Secretaría de Salud - CENAPRECE.</a></li>
            </ul>
        </div>
    </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-01">
                <span class="sr-only">Toggle navigation</span>
              </button>
              <a class="navbar-brand" href="#"><span class="fui-flat"></span></a>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse-01">
            <a class="navbar-brand" href=<%= root_path %>>Secretaría de Salud - Metas: Semana Nacional de Salud Bucal</a>
                <div class="collapse navbar-collapse" id="navbar-collapse-01">
                  <ul class="nav navbar-nav navbar-right">
                    <% if user_signed_in? %>
                    <li><%= link_to "Cerrar sesión",destroy_user_session_path, :method => :delete %></li>
                    <% else %>
                    <li><%= link_to "Ingresa", new_user_session_path %></li>
                    <% end %>
                  </ul>
                </div>
              </div><!-- /.navbar-collapse -->
            </nav><!-- /navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title>Captura de metas, salud Bucal</title>
      <%= stylesheet_link_tag "application", media: "all" %>
      <%= javascript_include_tag "application"%>
      <%= csrf_meta_tags %>
    </head>
    <body>
      <%= render 'layouts/header' %>
      <div class="container">
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
    </body>
  </html>